### ISSUE TITLE
A lot of XDXF, DSL, Stardict dictionaries

### ISSUE THREAD

**Issue by GD-fix** [itkach/xdxf2slob#3]
[There](http://booktracker.org/viewtopic.php?t=73067) ([mirror](http://uraltrack.net/viewtopic.php?t=23311)) is a lot of En-Ru, En-En, Ru-En and Ru-Ru dictionaries in XDXF, DSL, Stardict and other formats.

**Comment by itkach** [comment]
This is software issue tracker. For general discussion please use forum at http://aarddict.org/forum
